name = "seo-tools-internal"
compatibility_date = "2026-08-17"

[[d1_databases]]
binding = "DB"
database_name = "seo-tools-staging"
database_id = "ea3db656-3d94-4f8f-b819-5bd70abcbd64"
migrations_dir = "migrations"
