name = "seo-tools-internal"
main = ".open-next/worker.js"
compatibility_date = "2026-08-17"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "seo-tools-staging"
database_id = "ea3db656-3d94-4f8f-b819-5bd70abcbd64"
migrations_dir = "migrations"
