name = "seo-tool-fa"
compatibility_date = "2024-02-26"

# این همان کلیدی است که کلادفلر به شما داد
[[d1_databases]]
binding = "seogets_db"
database_name = "seogets-db"
database_id = "eeaa497c-f113-41f0-9efc-797d0becd110"